### PR TITLE
Add http handler

### LINKED ISSUE #8: Implement JsonRpcHttpConsumer?
Hi.

What about implementing another consumer, for http requests in the same fashion as websocket?

### LINKED ISSUE #9: Why threaded processing?
What is the reason for executing JsonRpc in separate threads?

### PR DESCRIPTION
**Pull request by millerf**
@soulhunter1987 can you please have a look at that?

closes #8, closes #9

### CODE REVIEW

**Comment by ekzobrain** [comment]
Looks good, except:
1. You should add transport parameters "websocket" and "http" to rpc_nofitication() along with rpc_method()
2. Two almost equal methods "__process_noficications" and "__process" should be replaced with one. But that's not the case now. We may leave up to dependency movement.
3. May be you are right about "kwargs", if user does not want to use it - he must have an ability to leave it out. I think we should return a check for function param "kwargs" and pass "original_exception" only if it is present.

**Comment by millerf** [comment]
.You should add transport parameters "websocket" and "http" to rpc_nofitication() along with rpc_method()

-> Good point. I forgot

Two almost equal methods "__process_nofications" and "__process" should be replaced with one. But that's not the case now. We may leave up to dependency movement.

-> Yes, I know they are almost duplicates. There is room for a lot of improvement.

May be you are right about "kwargs", if user does not want to use it - he must have an ability to leave it out. I think we should return a check for function param "kwargs" and pass "original_exception" only if it is present.

-> Can you really check for param "**kwargs"? 
It only is a problem if the rpc_method doesn't have any arguments at the first place. Maybe we should just check for that. Also, I couldn't find what you where talking about `environment` in Channels. I want to look into it. Do you have any link?

**Comment by ekzobrain** [comment]
Under "environment" I meant additional params, passed to event handlers by routing, for example.
If you capture some matches from routing rules - they would be passed to hadlers via kwargs on "websocket.connect" or "http.request" events. Ah, it would also be great to pass them through to rpc_method/notification handlers (then invoked through http). An example from my current project:

```python
channel_routing = [
    ButtonJsonRpcConsumer.as_route(path=r"^/button/v1/(?P<button_id>[a-zA-Z0-9\-]+)$"),
]
```
In our current implementation we can grab "button_id" inside JsonRpcConsumer.http_handler method, but it is not passed through to actual rpc handler. But if it was - we would have such a handler:

```python
@ButtonJsonRpcConsumer.rpc_handler()
def handler(param1, param2, **kwargs):
    original_message = kwargs['original_message']
    button_id = kwargs['button_id']
```
You see? kwargs contain additional params that a user may wish to grab from outside.

**Comment by millerf** [comment]
Ok, I just implemented that, so if `kwargs` is in the parameters it will be "filled" with original_message. If not, original_message will not be added.
I am not sure if I do it the right way, though... if parameter is not called `**kwargs` it won't work...

**Comment by ekzobrain** [comment]
I think it is OK for now, may be a better solution would come later by itself ) Currently it looks good enough

**Comment by millerf** [comment]
Yep.
Can you add a quick doc for your http_handler? So I can publish version 1.2?

**Comment by ekzobrain** [comment]
Merge it to master, please, then I will make a pull request with docs update

**Comment by millerf** [comment]
Done.

**Pull request merged**
