### PR TITLE
Add support for CORS in HTTP requests

### PR DESCRIPTION
**Pull request by ekzobrain**
Add transparent support for CORS in HTTP requests, via dependency library: django-cors-headers

### CODE REVIEW

**Comment by millerf** [comment]
I have an error in tests:
ImportError: No module named corsheaders.middleware
you are missing a dependency in requirements.txt

**Comment by ekzobrain** [comment]
Hm, did you run pip install? "django-cors-headers" is in there.

**Comment by millerf** [comment]
yes, the tests run pip install -r requirements.txt

**Comment by ekzobrain** [comment]
That's very strange, you may check yourself that requirements.txt is in this pull request and it contains django-cors-headers package

**Comment by ekzobrain** [comment]
But yes, I see error in tests myself. I will check that out also...

**Comment by millerf** [comment]
Weird... It is running it:

> Collecting django-cors-headers (from -r requirements.txt (line 5))
>   Downloading django_cors_headers-2.0.2-py2.py3-none-any.whlCollecting django-cors-headers (from -r requirements.txt (line 5))
>   Downloading django_cors_headers-2.0.2-py2.py3-none-any.whl

But then:


> ERROR: django_example.tests (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: django_example.tests
> Traceback (most recent call last):
>   File "/opt/python/3.6.1/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
>     module = self._get_module_from_name(name)
>   File "/opt/python/3.6.1/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
>     __import__(name)
>   File "/home/travis/build/millerf/django-channels-jsonrpc/example/django_example/tests.py", line 2, in <module>
>     from channels_jsonrpc import JsonRpcConsumerTest, JsonRpcException
>   File "/home/travis/build/millerf/django-channels-jsonrpc/.tox/coverage/lib/python3.6/site-packages/channels_jsonrpc/__init__.py", line 1, in <module>
>     from .jsonrpcconsumer import JsonRpcConsumer, JsonRpcConsumerTest, JsonRpcException
>   File "/home/travis/build/millerf/django-channels-jsonrpc/.tox/coverage/lib/python3.6/site-packages/channels_jsonrpc/jsonrpcconsumer.py", line 19, in <module>
>     from corsheaders.middleware import CorsMiddleware
> ModuleNotFoundError: No module named 'corsheaders'ERROR: django_example.tests (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: django_example.tests
> Traceback (most recent call last):
>   File "/opt/python/3.6.1/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
>     module = self._get_module_from_name(name)
>   File "/opt/python/3.6.1/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
>     __import__(name)
>   File "/home/travis/build/millerf/django-channels-jsonrpc/example/django_example/tests.py", line 2, in <module>
>     from channels_jsonrpc import JsonRpcConsumerTest, JsonRpcException
>   File "/home/travis/build/millerf/django-channels-jsonrpc/.tox/coverage/lib/python3.6/site-packages/channels_jsonrpc/__init__.py", line 1, in <module>
>     from .jsonrpcconsumer import JsonRpcConsumer, JsonRpcConsumerTest, JsonRpcException
>   File "/home/travis/build/millerf/django-channels-jsonrpc/.tox/coverage/lib/python3.6/site-packages/channels_jsonrpc/jsonrpcconsumer.py", line 19, in <module>
>     from corsheaders.middleware import CorsMiddleware
> ModuleNotFoundError: No module named 'corsheaders'



That happens on all python versions as well... 

See (not sure if you have access)
https://travis-ci.org/millerf/django-channels-jsonrpc/jobs/234817698

**Comment by millerf** [comment]
Ok, I tested locally and it works for me. I'll look into that.

**Comment by millerf** [comment]
Tests run locally but not when using tox

**Comment by millerf** [comment]
Found the error.

**Comment by millerf** [comment]
@soulhunter1987 What happened is that tox is building the package and test against it.
But you forgot to add dependencies in the setup.py :)

**Pull request merged**
